name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/nodejs.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/nodejs.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      #          cache: 'pnpm'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: "frontend/node_modules"
          key: node-modules-${{ hashFiles('frontend/package.json') }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Build
        working-directory: frontend
        run: pnpm run build

#      - name: Run tests
#        working-directory: frontend
#        run: pnpm test
